# for local development
version: '3.7'
services:
  frontend:
    build:
      context: .
      target: 'dev-stage'
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    command: npm run serve